# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "construct_object",
    "construct_object_json",
]

def construct_object(object_dict: dict) -> typing.Any:
    r"""
    Constructs a single python object from a PyImport dictionary
    
    Equivalent to ```unpack.construct_object_json(json.loads(json_str))```
    
    # Examples
    ```json
    {
        "object_import": "foo.bar.Baz",
        "data": {
            "x": 100.0,
            "complex": {
                "object_import": "foo.Foo",
                "data": {"a": [100.0]}
            },
            "pydantic_obj": {
                "a": 100.0,
                "b": {
                    "x": 100, "y": 100, "z": 100
                }
            }
        }
    }
    ```
    """

def construct_object_json(object_json_str: builtins.str) -> typing.Any:
    r"""
    Constructs a single python object from a serialized PyImport json string
    
    # Examples
    ```json
    {
        "object_import": "foo.bar.Baz",
        "data": {
            "x": 100.0,
            "complex": {
                "object_import": "foo.Foo",
                "data": {"a": [100.0]}
            },
            "pydantic_obj": {
                "a": 100.0,
                "b": {
                    "x": 100, "y": 100, "z": 100
                }
            }
        }
    }
    ```
    """

